services:
  - type: web
    name: stock-1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: HOST
        value: 0.0.0.0
